create table if not exists public.fitkline_analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  visitor_id uuid not null,
  session_id uuid not null,
  path text not null,
  referrer_host text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_category text not null default 'desktop'
    check (device_category in ('desktop', 'mobile', 'tablet')),
  constraint fitkline_analytics_path_length_check check (char_length(path) <= 300),
  constraint fitkline_analytics_referrer_length_check check (char_length(referrer_host) <= 180)
);

create index if not exists fitkline_analytics_occurred_at_idx
  on public.fitkline_analytics_events (occurred_at desc);
create index if not exists fitkline_analytics_visitor_idx
  on public.fitkline_analytics_events (visitor_id, occurred_at desc);
create index if not exists fitkline_analytics_session_idx
  on public.fitkline_analytics_events (session_id, occurred_at desc);
create index if not exists fitkline_analytics_path_idx
  on public.fitkline_analytics_events (path, occurred_at desc);

alter table public.fitkline_analytics_events enable row level security;
revoke all on public.fitkline_analytics_events from anon, authenticated;
grant all on public.fitkline_analytics_events to service_role;
grant usage, select on sequence public.fitkline_analytics_events_id_seq to service_role;

create or replace function public.fitkline_get_analytics(p_days integer default 30)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  v_days integer := greatest(7, least(coalesce(p_days, 30), 90));
  v_today date := timezone('Africa/Cairo', now())::date;
  v_start timestamptz;
  v_previous_start timestamptz;
  v_end timestamptz;
  v_visitors bigint;
  v_previous_visitors bigint;
  v_page_views bigint;
  v_previous_page_views bigint;
  v_sessions bigint;
  v_orders bigint;
begin
  v_start := (v_today - (v_days - 1))::timestamp at time zone 'Africa/Cairo';
  v_previous_start := (v_today - ((v_days * 2) - 1))::timestamp at time zone 'Africa/Cairo';
  v_end := (v_today + 1)::timestamp at time zone 'Africa/Cairo';

  select count(distinct visitor_id), count(*), count(distinct session_id)
  into v_visitors, v_page_views, v_sessions
  from public.fitkline_analytics_events
  where occurred_at >= v_start and occurred_at < v_end;

  select count(distinct visitor_id), count(*)
  into v_previous_visitors, v_previous_page_views
  from public.fitkline_analytics_events
  where occurred_at >= v_previous_start and occurred_at < v_start;

  select count(*) into v_orders
  from public.fitkline_orders
  where created_at >= v_start and created_at < v_end;

  return jsonb_build_object(
    'periodDays', v_days,
    'generatedAt', now(),
    'totals', jsonb_build_object(
      'allTimeVisitors', (select count(distinct visitor_id) from public.fitkline_analytics_events),
      'visitors', v_visitors,
      'previousVisitors', v_previous_visitors,
      'pageViews', v_page_views,
      'previousPageViews', v_previous_page_views,
      'sessions', v_sessions,
      'orders', v_orders,
      'averagePagesPerSession', case when v_sessions = 0 then 0 else round(v_page_views::numeric / v_sessions, 1) end,
      'conversionRate', case when v_visitors = 0 then 0 else round((v_orders::numeric * 100) / v_visitors, 1) end,
      'returningVisitors', (
        select count(*)
        from (
          select visitor_id
          from public.fitkline_analytics_events
          group by visitor_id
          having min(occurred_at) < v_start and max(occurred_at) >= v_start
        ) returning_visitors
      ),
      'singlePageSessions', (
        select count(*)
        from (
          select session_id
          from public.fitkline_analytics_events
          where occurred_at >= v_start and occurred_at < v_end
          group by session_id
          having count(*) = 1
        ) single_page
      )
    ),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object(
        'date', day::date,
        'visitors', coalesce(stats.visitors, 0),
        'pageViews', coalesce(stats.page_views, 0)
      ) order by day)
      from generate_series(v_today - (v_days - 1), v_today, interval '1 day') day
      left join lateral (
        select count(distinct visitor_id) visitors, count(*) page_views
        from public.fitkline_analytics_events
        where occurred_at >= day::timestamp at time zone 'Africa/Cairo'
          and occurred_at < (day + interval '1 day')::timestamp at time zone 'Africa/Cairo'
      ) stats on true
    ), '[]'::jsonb),
    'topPages', coalesce((
      select jsonb_agg(row_data order by views desc)
      from (
        select jsonb_build_object(
          'path', path,
          'views', count(*),
          'visitors', count(distinct visitor_id)
        ) row_data, count(*) views
        from public.fitkline_analytics_events
        where occurred_at >= v_start and occurred_at < v_end
        group by path
        order by count(*) desc
        limit 8
      ) pages
    ), '[]'::jsonb),
    'sources', coalesce((
      select jsonb_agg(row_data order by sessions desc)
      from (
        select jsonb_build_object(
          'source', coalesce(nullif(utm_source, ''), nullif(referrer_host, ''), 'direct'),
          'sessions', count(distinct session_id)
        ) row_data, count(distinct session_id) sessions
        from public.fitkline_analytics_events
        where occurred_at >= v_start and occurred_at < v_end
        group by coalesce(nullif(utm_source, ''), nullif(referrer_host, ''), 'direct')
        order by count(distinct session_id) desc
        limit 8
      ) traffic_sources
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object(
        'device', device_category,
        'visitors', visitors
      ) order by visitors desc)
      from (
        select device_category, count(distinct visitor_id) visitors
        from public.fitkline_analytics_events
        where occurred_at >= v_start and occurred_at < v_end
        group by device_category
      ) device_stats
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.fitkline_get_analytics(integer) from public, anon, authenticated;
grant execute on function public.fitkline_get_analytics(integer) to service_role;
